name: Flake Check

on:
  push:
    branches-ignore: [main, dev]
  pull_request:
    branches: [dev]

jobs:
  check:
    runs-on: [self-hosted, nixos]
    steps:
      - uses: actions/checkout@v4
      - name: Nix flake check
        run: nix flake check
